/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MyItemsRouteImport } from './routes/my-items'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiSearchRouteImport } from './routes/ai-search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsItemIdRouteImport } from './routes/items.$itemId'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyItemsRoute = MyItemsRouteImport.update({
  id: '/my-items',
  path: '/my-items',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSearchRoute = AiSearchRouteImport.update({
  id: '/ai-search',
  path: '/ai-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/my-items': typeof MyItemsRoute
  '/report': typeof ReportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/my-items': typeof MyItemsRoute
  '/report': typeof ReportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-search': typeof AiSearchRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/my-items': typeof MyItemsRoute
  '/report': typeof ReportRoute
  '/items/$itemId': typeof ItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-search'
    | '/auth'
    | '/browse'
    | '/my-items'
    | '/report'
    | '/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-search'
    | '/auth'
    | '/browse'
    | '/my-items'
    | '/report'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/'
    | '/ai-search'
    | '/auth'
    | '/browse'
    | '/my-items'
    | '/report'
    | '/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSearchRoute: typeof AiSearchRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  MyItemsRoute: typeof MyItemsRoute
  ReportRoute: typeof ReportRoute
  ItemsItemIdRoute: typeof ItemsItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-items': {
      id: '/my-items'
      path: '/my-items'
      fullPath: '/my-items'
      preLoaderRoute: typeof MyItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-search': {
      id: '/ai-search'
      path: '/ai-search'
      fullPath: '/ai-search'
      preLoaderRoute: typeof AiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$itemId': {
      id: '/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof ItemsItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSearchRoute: AiSearchRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  MyItemsRoute: MyItemsRoute,
  ReportRoute: ReportRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
